//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyGuide.APIRegistroNacional {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIRegistroNacional.Usuarios1Soap")]
    public interface Usuarios1Soap {
        
        // CODEGEN: Generating message contract since element name GetUsuariosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsuarios", ReplyAction="*")]
        BabyGuide.APIRegistroNacional.GetUsuariosResponse GetUsuarios(BabyGuide.APIRegistroNacional.GetUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<BabyGuide.APIRegistroNacional.GetUsuariosResponse> GetUsuariosAsync(BabyGuide.APIRegistroNacional.GetUsuariosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public BabyGuide.APIRegistroNacional.GetUsuariosRequestBody Body;
        
        public GetUsuariosRequest() {
        }
        
        public GetUsuariosRequest(BabyGuide.APIRegistroNacional.GetUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        public GetUsuariosRequestBody() {
        }
        
        public GetUsuariosRequestBody(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public BabyGuide.APIRegistroNacional.GetUsuariosResponseBody Body;
        
        public GetUsuariosResponse() {
        }
        
        public GetUsuariosResponse(BabyGuide.APIRegistroNacional.GetUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUsuariosResult;
        
        public GetUsuariosResponseBody() {
        }
        
        public GetUsuariosResponseBody(string GetUsuariosResult) {
            this.GetUsuariosResult = GetUsuariosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Usuarios1SoapChannel : BabyGuide.APIRegistroNacional.Usuarios1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Usuarios1SoapClient : System.ServiceModel.ClientBase<BabyGuide.APIRegistroNacional.Usuarios1Soap>, BabyGuide.APIRegistroNacional.Usuarios1Soap {
        
        public Usuarios1SoapClient() {
        }
        
        public Usuarios1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Usuarios1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Usuarios1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Usuarios1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BabyGuide.APIRegistroNacional.GetUsuariosResponse BabyGuide.APIRegistroNacional.Usuarios1Soap.GetUsuarios(BabyGuide.APIRegistroNacional.GetUsuariosRequest request) {
            return base.Channel.GetUsuarios(request);
        }
        
        public string GetUsuarios(int idUsuario) {
            BabyGuide.APIRegistroNacional.GetUsuariosRequest inValue = new BabyGuide.APIRegistroNacional.GetUsuariosRequest();
            inValue.Body = new BabyGuide.APIRegistroNacional.GetUsuariosRequestBody();
            inValue.Body.idUsuario = idUsuario;
            BabyGuide.APIRegistroNacional.GetUsuariosResponse retVal = ((BabyGuide.APIRegistroNacional.Usuarios1Soap)(this)).GetUsuarios(inValue);
            return retVal.Body.GetUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BabyGuide.APIRegistroNacional.GetUsuariosResponse> BabyGuide.APIRegistroNacional.Usuarios1Soap.GetUsuariosAsync(BabyGuide.APIRegistroNacional.GetUsuariosRequest request) {
            return base.Channel.GetUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BabyGuide.APIRegistroNacional.GetUsuariosResponse> GetUsuariosAsync(int idUsuario) {
            BabyGuide.APIRegistroNacional.GetUsuariosRequest inValue = new BabyGuide.APIRegistroNacional.GetUsuariosRequest();
            inValue.Body = new BabyGuide.APIRegistroNacional.GetUsuariosRequestBody();
            inValue.Body.idUsuario = idUsuario;
            return ((BabyGuide.APIRegistroNacional.Usuarios1Soap)(this)).GetUsuariosAsync(inValue);
        }
    }
}
